# Generated by Django 2.0.8 on 2019-02-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='', max_length=2000, verbose_name='description'),
            preserve_default=False,
        ),
    ]
